/* SPDX-License-Identifier: BSD-3-Clause */

#ifndef NRF_CMAKE_SDK_BOARD_H
#define NRF_CMAKE_SDK_BOARD_H

/* nRF54LM20 DK LED0 is active-high on P1.22. */
#define NRF_CMAKE_SDK_LED0_PORT NRF_P1
#define NRF_CMAKE_SDK_LED0_PIN 22u

/* VCOM1 is routed to UARTE20 through the DK interface MCU. */
#define NRF_CMAKE_SDK_VCOM_UARTE NRF_UARTE20
#define NRF_CMAKE_SDK_VCOM_TX_GPIO NRF_P1
#define NRF_CMAKE_SDK_VCOM_TX_PORT 1u
#define NRF_CMAKE_SDK_VCOM_TX_PIN 16u
#define NRF_CMAKE_SDK_VCOM_BAUDRATE UARTE_BAUDRATE_BAUDRATE_Baud115200

#endif
