/* SPDX-License-Identifier: BSD-3-Clause */
#ifndef NRFX_CONFIG_H__
#define NRFX_CONFIG_H__

/* Driver enable macros arrive through target usage requirements. Instance and
 * IRQ settings may be overridden by the consuming target's definitions. */
#ifndef NRFX_DEFAULT_IRQ_PRIORITY
#define NRFX_DEFAULT_IRQ_PRIORITY 7
#endif
#ifndef NRFX_PRS_ENABLED
#define NRFX_PRS_ENABLED 0
#endif

/* Reserved channels are excluded from the allocator. The fixed SDC masks are
 * traced in docs/provenance/m6-sdc-mpsl-contract.json; application claims add to
 * them instead of overriding the wireless owner's reservation. */
#ifndef NRFKIT_APP_DPPI00_CHANNELS_RESERVED
#define NRFKIT_APP_DPPI00_CHANNELS_RESERVED 0U
#endif
#if defined(NRFKIT_SDC_ENABLED) && NRFKIT_SDC_ENABLED
#define NRFKIT_DPPI00_CHANNELS_RESERVED (NRFKIT_APP_DPPI00_CHANNELS_RESERVED | 0x000aU)
#else
#define NRFKIT_DPPI00_CHANNELS_RESERVED NRFKIT_APP_DPPI00_CHANNELS_RESERVED
#endif
#ifndef NRFKIT_APP_DPPI00_GROUPS_RESERVED
#define NRFKIT_APP_DPPI00_GROUPS_RESERVED 0U
#endif
#if defined(NRFKIT_SDC_ENABLED) && NRFKIT_SDC_ENABLED
#define NRFKIT_DPPI00_GROUPS_RESERVED (NRFKIT_APP_DPPI00_GROUPS_RESERVED | 0U)
#else
#define NRFKIT_DPPI00_GROUPS_RESERVED NRFKIT_APP_DPPI00_GROUPS_RESERVED
#endif
#ifndef NRFKIT_APP_DPPI10_CHANNELS_RESERVED
#define NRFKIT_APP_DPPI10_CHANNELS_RESERVED 0U
#endif
#if defined(NRFKIT_SDC_ENABLED) && NRFKIT_SDC_ENABLED
#define NRFKIT_DPPI10_CHANNELS_RESERVED (NRFKIT_APP_DPPI10_CHANNELS_RESERVED | 0x0fffU)
#else
#define NRFKIT_DPPI10_CHANNELS_RESERVED NRFKIT_APP_DPPI10_CHANNELS_RESERVED
#endif
#ifndef NRFKIT_APP_DPPI10_GROUPS_RESERVED
#define NRFKIT_APP_DPPI10_GROUPS_RESERVED 0U
#endif
#if defined(NRFKIT_SDC_ENABLED) && NRFKIT_SDC_ENABLED
#define NRFKIT_DPPI10_GROUPS_RESERVED (NRFKIT_APP_DPPI10_GROUPS_RESERVED | 0U)
#else
#define NRFKIT_DPPI10_GROUPS_RESERVED NRFKIT_APP_DPPI10_GROUPS_RESERVED
#endif
#ifndef NRFKIT_APP_DPPI20_CHANNELS_RESERVED
#define NRFKIT_APP_DPPI20_CHANNELS_RESERVED 0U
#endif
#if defined(NRFKIT_SDC_ENABLED) && NRFKIT_SDC_ENABLED
#define NRFKIT_DPPI20_CHANNELS_RESERVED (NRFKIT_APP_DPPI20_CHANNELS_RESERVED | 0x0001U)
#else
#define NRFKIT_DPPI20_CHANNELS_RESERVED NRFKIT_APP_DPPI20_CHANNELS_RESERVED
#endif
#ifndef NRFKIT_APP_DPPI20_GROUPS_RESERVED
#define NRFKIT_APP_DPPI20_GROUPS_RESERVED 0U
#endif
#if defined(NRFKIT_SDC_ENABLED) && NRFKIT_SDC_ENABLED
#define NRFKIT_DPPI20_GROUPS_RESERVED (NRFKIT_APP_DPPI20_GROUPS_RESERVED | 0U)
#else
#define NRFKIT_DPPI20_GROUPS_RESERVED NRFKIT_APP_DPPI20_GROUPS_RESERVED
#endif
#ifndef NRFKIT_APP_DPPI30_CHANNELS_RESERVED
#define NRFKIT_APP_DPPI30_CHANNELS_RESERVED 0U
#endif
#if defined(NRFKIT_SDC_ENABLED) && NRFKIT_SDC_ENABLED
#define NRFKIT_DPPI30_CHANNELS_RESERVED (NRFKIT_APP_DPPI30_CHANNELS_RESERVED | 0U)
#else
#define NRFKIT_DPPI30_CHANNELS_RESERVED NRFKIT_APP_DPPI30_CHANNELS_RESERVED
#endif
#ifndef NRFKIT_APP_DPPI30_GROUPS_RESERVED
#define NRFKIT_APP_DPPI30_GROUPS_RESERVED 0U
#endif
#if defined(NRFKIT_SDC_ENABLED) && NRFKIT_SDC_ENABLED
#define NRFKIT_DPPI30_GROUPS_RESERVED (NRFKIT_APP_DPPI30_GROUPS_RESERVED | 0U)
#else
#define NRFKIT_DPPI30_GROUPS_RESERVED NRFKIT_APP_DPPI30_GROUPS_RESERVED
#endif
#ifndef NRFKIT_APP_GPIOTE20_CHANNELS_RESERVED
#define NRFKIT_APP_GPIOTE20_CHANNELS_RESERVED 0U
#endif
#define NRFX_GPIOTE20_CHANNELS_USED NRFKIT_APP_GPIOTE20_CHANNELS_RESERVED
#ifndef NRFKIT_APP_GPIOTE30_CHANNELS_RESERVED
#define NRFKIT_APP_GPIOTE30_CHANNELS_RESERVED 0U
#endif
#define NRFX_GPIOTE30_CHANNELS_USED NRFKIT_APP_GPIOTE30_CHANNELS_RESERVED
#if defined(CONFIG_NRFX_GPIOTE_NUM_OF_EVT_HANDLERS) && !defined(NRFX_GPIOTE_CONFIG_NUM_OF_EVT_HANDLERS)
#define NRFX_GPIOTE_CONFIG_NUM_OF_EVT_HANDLERS CONFIG_NRFX_GPIOTE_NUM_OF_EVT_HANDLERS
#endif
#include <templates/nrfx_config_common.h>
#include <bsp/stable/templates/nrfx_config_nrf54lm20a_application.h>
#include <soc/nrfx_irqs.h>
#endif
