// SPDX-License-Identifier: BSD-3-Clause

#ifndef NRFKIT_VERSION_H_
#define NRFKIT_VERSION_H_

#define NRFKIT_VERSION_MAJOR 0
#define NRFKIT_VERSION_MINOR 0
#define NRFKIT_VERSION_PATCH 0
#define NRFKIT_VERSION_STRING "0.0.0"

#endif
