// SPDX-License-Identifier: BSD-3-Clause

#ifndef NRF_CMAKE_SDK_VERSION_H_
#define NRF_CMAKE_SDK_VERSION_H_

#define NRF_CMAKE_SDK_VERSION_MAJOR 0
#define NRF_CMAKE_SDK_VERSION_MINOR 0
#define NRF_CMAKE_SDK_VERSION_PATCH 0
#define NRF_CMAKE_SDK_VERSION_STRING "0.0.0"

#endif
