# SPDX-License-Identifier: BSD-3-Clause

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(NRF_LLVM_ROOT "" CACHE PATH "LLVM installation prefix")
find_program(CMAKE_C_COMPILER NAMES clang HINTS "${NRF_LLVM_ROOT}" PATH_SUFFIXES bin REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES clang++ HINTS "${NRF_LLVM_ROOT}" PATH_SUFFIXES bin REQUIRED)
find_program(CMAKE_ASM_COMPILER NAMES clang HINTS "${NRF_LLVM_ROOT}" PATH_SUFFIXES bin REQUIRED)
find_program(CMAKE_LINKER NAMES ld.lld HINTS "${NRF_LLVM_ROOT}" PATH_SUFFIXES bin REQUIRED)
find_program(CMAKE_OBJCOPY NAMES llvm-objcopy HINTS "${NRF_LLVM_ROOT}" PATH_SUFFIXES bin REQUIRED)
find_program(CMAKE_READELF NAMES llvm-readelf HINTS "${NRF_LLVM_ROOT}" PATH_SUFFIXES bin REQUIRED)
find_program(CMAKE_OBJDUMP NAMES llvm-objdump HINTS "${NRF_LLVM_ROOT}" PATH_SUFFIXES bin REQUIRED)

set(CMAKE_C_COMPILER_TARGET arm-none-eabi)
set(CMAKE_CXX_COMPILER_TARGET arm-none-eabi)
set(CMAKE_ASM_COMPILER_TARGET arm-none-eabi)
